export const stellarDemo = {
  company: {
    name: "Stellar",
    employees: 50,
    currentSaasSpend: 100000,
    stackPrice: 70000,
    currentMonth: 14,
  },
  metrics: {
    monthlySavings: 32350,
    toolsReplaced: 11,
    toolsTotal: 23,
    activeWorkflows: 47,
    documentsThisWeek: 283,
  },
  activity: [
    { time: "3 min ago", text: 'Sara commented on "Q2 Revenue Review"', source: "documents" },
    { time: "12 min ago", text: "New invoice: Airtame AB, 4,500 SEK", source: "fortnox" },
    { time: "34 min ago", text: "Weekly report generated by .stack", source: "agent" },
    { time: "1h ago", text: 'Mikaela \u2192 Anton: "Can you look at the Svenska Spel brief?"', source: "inbox" },
    { time: "2h ago", text: "Meeting prep completed for Monday", source: "agent" },
  ],
  inbox: [
    { source: "slack", from: "Team", preview: "New lead from the Brand Factory call, they want to see a proposal by Friday", time: "5 min ago" },
    { source: "email", from: "Mikaela Lindgren", preview: "Approved the Svenska Spel brief, moving to production", time: "22 min ago" },
    { source: "hubspot", from: "Lead notification", preview: "John @ Nordic Logistics viewed your proposal 3 times", time: "1h ago" },
    { source: "fortnox", from: "Invoice alert", preview: "Due in 5 days: Meta Platforms, 87,400 SEK", time: "2h ago" },
    { source: "slack", from: "Sara \u2192 #team-perf", preview: "Q2 numbers are locked, I'll share the dashboard", time: "3h ago" },
    { source: "notion", from: "Mention", preview: 'Anton was mentioned in "Performance Q2 review"', time: "5h ago" },
    { source: "clickup", from: "Task update", preview: '"Prepare Brand Factory proposal" moved to In Progress', time: "6h ago" },
  ],
  finance: {
    revenueThisMonth: 4280000,
    expensesThisMonth: 2140000,
    saasCosts: 67650,
    saasChange: -0.32,
    replacedTools: [
      { name: "HubSpot Pro", before: "4 seats", after: "0 seats", saving: 9600, note: "replaced with .stack CRM module" },
      { name: "Monday Pro", before: "12 seats", after: "0 seats", saving: 8400, note: "replaced with .stack Projects" },
      { name: "Notion Team", before: "50 seats", after: "10 seats", saving: 3200, note: "consolidated into .stack Documents" },
      { name: "ClickUp Business", before: "30 seats", after: "0 seats", saving: 5400, note: "replaced with .stack Projects" },
      { name: "Slack Pro", before: "50 seats", after: "5 seats", saving: 4800, note: "external-only, internal via .stack" },
    ],
  },
  agentConversation: [
    {
      role: "user" as const,
      content: "Show me every time a client mentioned renewing their contract this month.",
    },
    {
      role: "assistant" as const,
      content: `Looking across your inbox, Slack, and HubSpot. Found 4 instances.

1. Brand Factory, April 3: "We'd like to discuss renewing for another 12 months"
   Source: Email, Mikaela Andersson

2. Nordic Logistics, April 8: Mentioned contract extension in Slack #clients
   Source: Slack, John Karlsson

3. Svenska Spel, April 11: Renewal flagged on HubSpot deal
   Source: HubSpot, renewal due June

4. 100.se, April 15: Sent counter-offer for new 24-month term
   Source: Email thread, Sara Lindqvist`,
    },
    {
      role: "user" as const,
      content: "Draft a proactive response to Brand Factory showing we're ready to discuss.",
    },
    {
      role: "assistant" as const,
      content: `Drafting.

Subject: Re: Contract renewal, our proposal

Hi Mikaela,

Thanks for bringing up the renewal conversation. We've been tracking the results of the last 12 months closely and I think there's a strong case for continuing, with some expansions.

Here's what I'm proposing:
- A 12-month renewal at the current pricing tier
- Addition of the new performance analytics module (launched Q1) at no extra cost for the first 6 months
- A quarterly business review structure so we can align on metrics together

Happy to jump on a call this week to walk through it. Wednesday or Thursday afternoon works on my end.

Best,
Anton

Would you like me to send this to Mikaela, or would you like to review and edit first?`,
    },
  ],
};
