// ============================================================
// .stack App Store
// Every app here replaces a specific SaaS category.
// "installed" apps map to modulesEnabled on spaces.
// "available" apps are what customers can add.
// ============================================================

export type AppCategory =
  | "communication"
  | "productivity"
  | "marketing"
  | "sales"
  | "finance"
  | "hr"
  | "engineering"
  | "design"
  | "analytics"
  | "security"
  | "operations"
  | "support";

export interface StoreApp {
  id: string;
  name: string;
  description: string;
  category: AppCategory;
  replaces: string[];       // SaaS tools this replaces
  icon: string;             // Lucide icon name
  builtIn: boolean;         // Already built into .stack
  moduleId?: string;        // maps to modulesEnabled key if built-in
  roles: string[];          // which roles benefit from this
  popular: boolean;
  pricing: "included" | "add-on";
}

export const categoryLabels: Record<AppCategory, string> = {
  communication: "Communication",
  productivity: "Productivity",
  marketing: "Marketing & Ads",
  sales: "Sales & CRM",
  finance: "Finance & Billing",
  hr: "People & HR",
  engineering: "Engineering",
  design: "Design & Creative",
  analytics: "Analytics & BI",
  security: "Security & Compliance",
  operations: "Operations",
  support: "Support & Service",
};

export const categoryDescriptions: Record<AppCategory, string> = {
  communication: "Replace Slack, Teams, email clients, and video tools with unified messaging.",
  productivity: "Replace Notion, Monday, Asana, ClickUp, and other project/doc tools.",
  marketing: "Replace HubSpot Marketing, Mailchimp, Meta Business Suite, and campaign tools.",
  sales: "Replace HubSpot CRM, Salesforce, Pipedrive, and deal management tools.",
  finance: "Replace Fortnox UI, Xero, QuickBooks, and billing/invoicing tools.",
  hr: "Replace BambooHR, Personio, and people management tools.",
  engineering: "Replace Jira, Linear, GitHub Issues, and dev workflow tools.",
  design: "Replace Figma workflows, Canva, and creative production tools.",
  analytics: "Replace Google Analytics dashboards, Looker, and BI tools.",
  security: "Replace 1Password Business, Vanta, and compliance tools.",
  operations: "Replace Zapier, Make, and operational automation tools.",
  support: "Replace Zendesk, Intercom, and customer support tools.",
};

export const storeApps: StoreApp[] = [
  // ── Communication ──────────────────────────────────────────
  {
    id: "conversations",
    name: "Conversations",
    description: "Unified inbox across email, Slack, and meeting notes. Every client thread in one place.",
    category: "communication",
    replaces: ["Slack", "Microsoft Teams", "Front"],
    icon: "MessageSquare",
    builtIn: true,
    moduleId: "conversations",
    roles: ["all"],
    popular: true,
    pricing: "included",
  },
  {
    id: "chat",
    name: "Team Chat",
    description: "Real-time channels per space. Internal discussions without leaving .stack.",
    category: "communication",
    replaces: ["Slack", "Microsoft Teams", "Discord"],
    icon: "MessagesSquare",
    builtIn: true,
    moduleId: "chat",
    roles: ["all"],
    popular: true,
    pricing: "included",
  },
  {
    id: "video-calls",
    name: "Video Calls",
    description: "Built-in video meetings with transcription, summaries, and automatic action items.",
    category: "communication",
    replaces: ["Zoom", "Google Meet", "Microsoft Teams"],
    icon: "Video",
    builtIn: false,
    roles: ["all"],
    popular: true,
    pricing: "included",
  },
  {
    id: "email-client",
    name: "Email",
    description: "Full email client with AI-powered drafting, scheduling, and smart categorization.",
    category: "communication",
    replaces: ["Gmail", "Outlook", "Superhuman", "Spark"],
    icon: "Mail",
    builtIn: false,
    roles: ["all"],
    popular: true,
    pricing: "included",
  },

  // ── Productivity ───────────────────────────────────────────
  {
    id: "projects",
    name: "Projects",
    description: "Kanban boards, task management, and progress tracking with time estimates.",
    category: "productivity",
    replaces: ["Asana", "Monday.com", "ClickUp", "Trello"],
    icon: "KanbanSquare",
    builtIn: true,
    moduleId: "projects",
    roles: ["project manager", "all"],
    popular: true,
    pricing: "included",
  },
  {
    id: "files",
    name: "Files & Docs",
    description: "File storage with AI tagging, semantic search, and inline previews.",
    category: "productivity",
    replaces: ["Google Drive", "Dropbox", "Notion", "Confluence"],
    icon: "FolderOpen",
    builtIn: true,
    moduleId: "files",
    roles: ["all"],
    popular: true,
    pricing: "included",
  },
  {
    id: "calendar",
    name: "Calendar",
    description: "Unified calendar across all spaces with smart scheduling and prep notes.",
    category: "productivity",
    replaces: ["Google Calendar", "Outlook Calendar", "Calendly"],
    icon: "Calendar",
    builtIn: true,
    moduleId: "calendar",
    roles: ["all"],
    popular: true,
    pricing: "included",
  },
  {
    id: "timeline",
    name: "Timeline",
    description: "Gantt-style project timelines with phase tracking and milestone markers.",
    category: "productivity",
    replaces: ["Smartsheet", "TeamGantt", "Monday Timeline"],
    icon: "GanttChart",
    builtIn: true,
    moduleId: "timeline",
    roles: ["project manager", "leadership"],
    popular: false,
    pricing: "included",
  },
  {
    id: "notes",
    name: "Notes & Wiki",
    description: "Team knowledge base with real-time collaboration and AI-powered organization.",
    category: "productivity",
    replaces: ["Notion", "Confluence", "Slite", "Almanac"],
    icon: "BookOpen",
    builtIn: false,
    roles: ["all"],
    popular: true,
    pricing: "included",
  },
  {
    id: "forms",
    name: "Forms & Surveys",
    description: "Client intake forms, internal surveys, and feedback collection.",
    category: "productivity",
    replaces: ["Typeform", "Google Forms", "SurveyMonkey"],
    icon: "ClipboardList",
    builtIn: false,
    roles: ["operations", "hr"],
    popular: false,
    pricing: "included",
  },
  {
    id: "whiteboards",
    name: "Whiteboards",
    description: "Collaborative visual canvases for brainstorming and planning sessions.",
    category: "productivity",
    replaces: ["Miro", "FigJam", "Mural"],
    icon: "PenTool",
    builtIn: false,
    roles: ["design", "strategy"],
    popular: false,
    pricing: "included",
  },

  // ── Marketing & Ads ────────────────────────────────────────
  {
    id: "campaigns",
    name: "Campaigns",
    description: "Multi-channel ad campaign management across Meta, Google, TikTok with live metrics.",
    category: "marketing",
    replaces: ["Meta Business Suite", "Google Ads Manager", "TikTok Ads"],
    icon: "Megaphone",
    builtIn: true,
    moduleId: "campaigns",
    roles: ["marketing", "performance"],
    popular: true,
    pricing: "included",
  },
  {
    id: "email-marketing",
    name: "Email Marketing",
    description: "Newsletter campaigns, drip sequences, and audience segmentation.",
    category: "marketing",
    replaces: ["Mailchimp", "Brevo", "ActiveCampaign", "Klaviyo"],
    icon: "Send",
    builtIn: false,
    roles: ["marketing"],
    popular: true,
    pricing: "add-on",
  },
  {
    id: "social-media",
    name: "Social Media",
    description: "Schedule, publish, and analyze content across all social platforms.",
    category: "marketing",
    replaces: ["Hootsuite", "Buffer", "Sprout Social", "Later"],
    icon: "Share2",
    builtIn: false,
    roles: ["marketing", "content"],
    popular: true,
    pricing: "included",
  },
  {
    id: "seo",
    name: "SEO & Content",
    description: "Keyword tracking, site audits, content optimization, and rank monitoring.",
    category: "marketing",
    replaces: ["Ahrefs", "SEMrush", "Moz", "Surfer SEO"],
    icon: "Search",
    builtIn: false,
    roles: ["marketing", "content"],
    popular: false,
    pricing: "add-on",
  },
  {
    id: "landing-pages",
    name: "Landing Pages",
    description: "Build and A/B test landing pages without developers.",
    category: "marketing",
    replaces: ["Unbounce", "Leadpages", "Instapage"],
    icon: "LayoutTemplate",
    builtIn: false,
    roles: ["marketing"],
    popular: false,
    pricing: "add-on",
  },

  // ── Sales & CRM ────────────────────────────────────────────
  {
    id: "crm",
    name: "CRM",
    description: "Contact management, deal pipeline, interaction history, and company profiles.",
    category: "sales",
    replaces: ["HubSpot CRM", "Salesforce", "Pipedrive"],
    icon: "Users",
    builtIn: true,
    moduleId: "crm",
    roles: ["sales", "account management", "all"],
    popular: true,
    pricing: "included",
  },
  {
    id: "proposals",
    name: "Proposals & Quotes",
    description: "Create branded proposals with e-signatures and real-time tracking.",
    category: "sales",
    replaces: ["PandaDoc", "Proposify", "Qwilr"],
    icon: "FileSignature",
    builtIn: false,
    roles: ["sales", "account management"],
    popular: true,
    pricing: "included",
  },
  {
    id: "contracts",
    name: "Contracts",
    description: "Contract lifecycle management with templates, approval workflows, and e-sign.",
    category: "sales",
    replaces: ["DocuSign", "Oneflow", "Contractbook"],
    icon: "FileCheck",
    builtIn: false,
    roles: ["sales", "legal", "leadership"],
    popular: false,
    pricing: "add-on",
  },
  {
    id: "lead-scoring",
    name: "Lead Scoring",
    description: "AI-powered lead qualification based on engagement, fit, and intent signals.",
    category: "sales",
    replaces: ["HubSpot Lead Scoring", "Clearbit", "6sense"],
    icon: "Target",
    builtIn: false,
    roles: ["sales"],
    popular: false,
    pricing: "add-on",
  },

  // ── Finance & Billing ──────────────────────────────────────
  {
    id: "finance",
    name: "Finance",
    description: "Invoicing, expense tracking, time-based billing, and project economics.",
    category: "finance",
    replaces: ["Harvest", "Toggl Track", "FreshBooks"],
    icon: "CreditCard",
    builtIn: true,
    moduleId: "finance",
    roles: ["finance", "leadership", "project manager"],
    popular: true,
    pricing: "included",
  },
  {
    id: "expense-management",
    name: "Expense Management",
    description: "Receipt scanning, expense reports, approval workflows, and reimbursements.",
    category: "finance",
    replaces: ["Pleo", "Spendesk", "Expensify"],
    icon: "Receipt",
    builtIn: false,
    roles: ["finance", "all"],
    popular: true,
    pricing: "included",
  },
  {
    id: "payroll",
    name: "Payroll",
    description: "Salary processing, tax calculations, and payment automation.",
    category: "finance",
    replaces: ["Hogia Lön", "Visma Lön", "Gusto"],
    icon: "Banknote",
    builtIn: false,
    roles: ["hr", "finance"],
    popular: false,
    pricing: "add-on",
  },
  {
    id: "subscription-tracker",
    name: "Subscription Tracker",
    description: "Monitor all company SaaS subscriptions, flag unused seats, and optimize spend.",
    category: "finance",
    replaces: ["Cledara", "Zylo", "Productiv"],
    icon: "RefreshCw",
    builtIn: false,
    roles: ["finance", "operations", "leadership"],
    popular: true,
    pricing: "included",
  },

  // ── People & HR ────────────────────────────────────────────
  {
    id: "people",
    name: "People",
    description: "Employee directory, org chart, time-off tracking, and 1:1 management.",
    category: "hr",
    replaces: ["BambooHR", "Personio", "HiBob"],
    icon: "Users",
    builtIn: false,
    roles: ["hr", "leadership"],
    popular: true,
    pricing: "included",
  },
  {
    id: "recruiting",
    name: "Recruiting",
    description: "Job postings, applicant tracking, interview scheduling, and scorecards.",
    category: "hr",
    replaces: ["Teamtailor", "Greenhouse", "Lever"],
    icon: "UserPlus",
    builtIn: false,
    roles: ["hr", "leadership"],
    popular: true,
    pricing: "add-on",
  },
  {
    id: "onboarding",
    name: "Onboarding",
    description: "Automated onboarding workflows, checklists, and new hire experience.",
    category: "hr",
    replaces: ["Sapling", "Enboarder", "Notion templates"],
    icon: "GraduationCap",
    builtIn: false,
    roles: ["hr"],
    popular: false,
    pricing: "included",
  },
  {
    id: "performance",
    name: "Performance Reviews",
    description: "360 reviews, OKR tracking, goal setting, and continuous feedback.",
    category: "hr",
    replaces: ["Lattice", "15Five", "Culture Amp"],
    icon: "TrendingUp",
    builtIn: false,
    roles: ["hr", "leadership"],
    popular: false,
    pricing: "add-on",
  },

  // ── Engineering ────────────────────────────────────────────
  {
    id: "issue-tracker",
    name: "Issue Tracker",
    description: "Bug tracking, feature requests, and sprint planning for dev teams.",
    category: "engineering",
    replaces: ["Jira", "Linear", "GitHub Issues", "Shortcut"],
    icon: "Bug",
    builtIn: false,
    roles: ["engineering"],
    popular: true,
    pricing: "included",
  },
  {
    id: "docs-api",
    name: "API Docs",
    description: "Auto-generated API documentation with interactive testing.",
    category: "engineering",
    replaces: ["Readme", "Stoplight", "Swagger"],
    icon: "Code",
    builtIn: false,
    roles: ["engineering"],
    popular: false,
    pricing: "included",
  },
  {
    id: "status-page",
    name: "Status Page",
    description: "Public and internal status pages with incident management.",
    category: "engineering",
    replaces: ["Statuspage", "Instatus", "Betteruptime"],
    icon: "Activity",
    builtIn: false,
    roles: ["engineering", "operations"],
    popular: false,
    pricing: "included",
  },

  // ── Design & Creative ──────────────────────────────────────
  {
    id: "creative",
    name: "Creative Studio",
    description: "AI-powered image generation, creative briefs, and brand asset management.",
    category: "design",
    replaces: ["Canva", "Adobe Express", "Midjourney"],
    icon: "Palette",
    builtIn: true,
    moduleId: "creative",
    roles: ["design", "marketing"],
    popular: true,
    pricing: "included",
  },
  {
    id: "brand-kit",
    name: "Brand Kit",
    description: "Centralized brand guidelines, logos, colors, fonts, and templates.",
    category: "design",
    replaces: ["Frontify", "Brandfolder", "Bynder"],
    icon: "Paintbrush",
    builtIn: false,
    roles: ["design", "marketing"],
    popular: false,
    pricing: "included",
  },
  {
    id: "video-editor",
    name: "Video Editor",
    description: "Quick video editing, trimming, subtitles, and format conversion.",
    category: "design",
    replaces: ["Descript", "CapCut Pro", "Adobe Premiere Rush"],
    icon: "Film",
    builtIn: false,
    roles: ["design", "marketing", "content"],
    popular: false,
    pricing: "add-on",
  },

  // ── Analytics & BI ─────────────────────────────────────────
  {
    id: "reports",
    name: "Reports",
    description: "AI-generated reports with charts, tables, and scheduling.",
    category: "analytics",
    replaces: ["Google Data Studio", "Databox", "Geckoboard"],
    icon: "BarChart3",
    builtIn: true,
    moduleId: "reports",
    roles: ["marketing", "leadership", "all"],
    popular: true,
    pricing: "included",
  },
  {
    id: "dashboards",
    name: "Custom Dashboards",
    description: "Build custom dashboards pulling data from any module or integration.",
    category: "analytics",
    replaces: ["Looker", "Metabase", "Klipfolio"],
    icon: "LayoutDashboard",
    builtIn: false,
    roles: ["analytics", "leadership"],
    popular: true,
    pricing: "add-on",
  },
  {
    id: "web-analytics",
    name: "Web Analytics",
    description: "Privacy-first website analytics with conversion tracking.",
    category: "analytics",
    replaces: ["Google Analytics", "Plausible", "Fathom"],
    icon: "Globe",
    builtIn: false,
    roles: ["marketing", "engineering"],
    popular: true,
    pricing: "add-on",
  },

  // ── Security & Compliance ──────────────────────────────────
  {
    id: "passwords",
    name: "Password Manager",
    description: "Shared vaults, secure credential sharing, and SSO management.",
    category: "security",
    replaces: ["1Password Business", "LastPass", "Dashlane"],
    icon: "KeyRound",
    builtIn: false,
    roles: ["all"],
    popular: true,
    pricing: "included",
  },
  {
    id: "compliance",
    name: "Compliance Manager",
    description: "GDPR, SOC2, and industry compliance tracking with audit trails.",
    category: "security",
    replaces: ["Vanta", "Drata", "Sprinto"],
    icon: "ShieldCheck",
    builtIn: false,
    roles: ["legal", "security", "leadership"],
    popular: false,
    pricing: "add-on",
  },
  {
    id: "audit-log",
    name: "Audit Log",
    description: "Complete activity trail across all .stack modules.",
    category: "security",
    replaces: ["Built into enterprise SaaS"],
    icon: "ScrollText",
    builtIn: false,
    roles: ["security", "leadership"],
    popular: false,
    pricing: "included",
  },

  // ── Operations ─────────────────────────────────────────────
  {
    id: "automations",
    name: "Automations",
    description: "If-this-then-that workflows across all .stack modules. No code needed.",
    category: "operations",
    replaces: ["Zapier", "Make", "n8n", "Power Automate"],
    icon: "Workflow",
    builtIn: false,
    roles: ["operations", "all"],
    popular: true,
    pricing: "included",
  },
  {
    id: "integrations",
    name: "Integrations Hub",
    description: "Connect external tools via API. Bring in data from any SaaS that hasn't been replaced yet.",
    category: "operations",
    replaces: ["Zapier", "Tray.io"],
    icon: "Plug",
    builtIn: false,
    roles: ["operations", "engineering"],
    popular: true,
    pricing: "included",
  },
  {
    id: "inventory",
    name: "Inventory",
    description: "Track physical inventory, orders, and warehouse operations.",
    category: "operations",
    replaces: ["TradeGecko", "Cin7", "inFlow"],
    icon: "Package",
    builtIn: false,
    roles: ["operations", "logistics"],
    popular: false,
    pricing: "add-on",
  },

  // ── Support & Service ──────────────────────────────────────
  {
    id: "helpdesk",
    name: "Help Desk",
    description: "Ticket management, knowledge base, and customer communication.",
    category: "support",
    replaces: ["Zendesk", "Freshdesk", "Help Scout"],
    icon: "LifeBuoy",
    builtIn: false,
    roles: ["support", "operations"],
    popular: true,
    pricing: "included",
  },
  {
    id: "live-chat",
    name: "Live Chat",
    description: "Website chat widget with AI auto-responses and handoff to team.",
    category: "support",
    replaces: ["Intercom", "Drift", "Crisp"],
    icon: "MessageCircle",
    builtIn: false,
    roles: ["support", "sales"],
    popular: true,
    pricing: "add-on",
  },
  {
    id: "knowledge-base",
    name: "Knowledge Base",
    description: "Public and internal knowledge base with AI-powered search.",
    category: "support",
    replaces: ["Notion public pages", "GitBook", "Document360"],
    icon: "Library",
    builtIn: false,
    roles: ["support", "all"],
    popular: false,
    pricing: "included",
  },
];

// Helpers
export function getAppsByCategory(category: AppCategory) {
  return storeApps.filter((a) => a.category === category);
}

export function getInstalledApps(modulesEnabled: string[]) {
  return storeApps.filter((a) => a.builtIn && a.moduleId && modulesEnabled.includes(a.moduleId));
}

export function getAvailableApps(modulesEnabled: string[]) {
  return storeApps.filter((a) => !a.builtIn || !a.moduleId || !modulesEnabled.includes(a.moduleId));
}

export const allCategories = Object.keys(categoryLabels) as AppCategory[];
